### ISSUE TITLE
Diagrama de Clases y Secuencia

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equpio-lor-xd#1]
[DiagramasDeClasesYSecuencia.pdf](https://github.com/user-attachments/files/18018142/DiagramasDeClasesYSecuencia.pdf)

**Comment by Reyesjessica** [comment]
18

**Comment by Reyesjessica** [comment]
28 cumple con casi todo lo requerido

**Comment by josealfredo79** [comment]
Faltan los diagramas de secuencia,..solo se muestra 1 diagrama

**Comment by 22620188Oliverio** [comment]
Se han agregado los diagramas de secuencia que faltaban <br>
[DiagramasDeClasesYSecuencia.pdf](https://github.com/user-attachments/files/18086315/DiagramasDeClasesYSecuencia.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
